### ISSUE TITLE
Send e-mail with the content

### ISSUE THREAD

**Issue by matheus-rambo** [matheus-rambo/r_crypto#2]
We should add an option to let user send an e-mail with the content encrypted/decrypted

**Comment by punishercoder** [comment]
When send an e-mail, the user may have the choice to use his PGP public key, so wen can send the content encrypted with his own public key.
If the user does not have, we will send it as plain text.

[PGP](https://cets.seas.upenn.edu/answers/pgp_keys.html)
[OPEN PGP](https://www.openpgp.org/software/)
