### ISSUE TITLE
Error when trying to encrypt a image file

### ISSUE THREAD

**Issue by matheus-rambo** [matheus-rambo/r_crypto#20]
This is my problem: UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte

**Comment by punishercoder** [comment]
We can open the file as a byte file, so, we can encrypt/decrypt the byte directly. 
If we do that, maybe we will loose the way to add info about the file, like adding the user that encrypted.

**Comment by matheus-rambo** [comment]
Fixed: https://github.com/matheus-rambo/r_crypto/commit/6c7e78e2abcea9c081b249de67ab19a9e0c29e2a
