### ISSUE TITLE
Diretórios criptografados devem voltar a sua estrutura original após a sua descriptografia

### ISSUE THREAD

**Issue by ArthurBottcher** [matheus-rambo/r_crypto#53]

**Comment by ArthurBottcher** [comment]
Salvar a estrutura do diretório criptografado e manter a estrutura após descriptografar.
Exemplo 
dir 1
 | -arq1
 | -arq2
dir2
 | -arq3
 | -dir3
    | -arq4

**Comment by matheus-rambo** [comment]
Solução prevista: Criar uma cópia do diretório
