### ISSUE TITLE
Salvar os arquivos criptografados/descriptografados em outro diretório.

### ISSUE THREAD

**Issue by ArthurBottcher** [matheus-rambo/r_crypto#56]
Atualmente o programa salva os arquivos criptografados no diretório onde o usuário se encontra.
Colocar a opção para o usuário escolher o diretório, digitando o caminho ou com um default salvando no diretório do usuário ou do arquivo original.

**Comment by matheus-rambo** [comment]
Já é possível fazer isso.
Para realizar, ao invés de colocar apenas o nome do arquivo, o usuário pode colocar o caminho absoluto.
